import React, { useRef } from "react";
import { useFrame, extend } from "@react-three/fiber";
import { shaderMaterial } from "@react-three/drei";
import * as THREE from "three";

/**
 * Simple animated water surface using a custom shader.
 * The vertex displacement creates a wave‑like motion.
 * The fragment shader applies a semi‑transparent blue colour.
 */
const WaterMat = shaderMaterial(
  // uniform defaults
  { uTime: 0, uColor: new THREE.Color("#00B4D8") },
  // vertex shader
  `uniform float uTime;
   varying vec2 vUv;
   void main() {
     vUv = uv;
     vec3 pos = position;
     float freq = 2.0;
     float amp = 0.2;
     pos.z += sin(pos.x * freq + uTime) * amp;
     pos.y += sin(pos.x * freq + uTime * 0.7) * amp * 0.5;
     gl_Position = projectionMatrix * modelViewMatrix * vec4(pos, 1.0);
   }`,
  // fragment shader
  `uniform vec3 uColor;
   varying vec2 vUv;
   void main() {
     gl_FragColor = vec4(uColor, 0.6);
   }`
);

// Register so <waterMat> becomes a JSX element
extend({ WaterMat });

type WaterSurfaceProps = {
  size?: number;
};

export const WaterSurface: React.FC<WaterSurfaceProps> = ({ size = 20 }) => {
  const matRef = useRef<any>();
  useFrame((state) => {
    if (matRef.current) matRef.current.uTime = state.clock.getElapsedTime();
  });

  return (
    <mesh rotation-x={-Math.PI / 2} position={[0, -0.4, 0]}>
      <planeGeometry args={[size, size, 128, 128]} />
      {/* @ts-ignore – the custom element name is generated by extend */}
      <waterMat ref={matRef} uColor={new THREE.Color("#00B4D8")} />
    </mesh>
  );
};
